# Generated by Django 5.2.7 on 2025-10-19 07:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.CharField(choices=[('avatar1.png', 'Avatar 1'), ('avatar2.png', 'Avatar 2'), ('avatar3.png', 'Avatar 3'), ('avatar4.png', 'Avatar 4')], default=('avatar2.png', 'Avatar 2'), max_length=50)),
                ('tokens', models.IntegerField(default=3)),
                ('last_reset', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
